### ISSUE TITLE
用个17年的ppt再买点star引流，最后其实是广告？

### ISSUE THREAD

**Issue by JiangWen002** [0voice/from_coder_to_expert#9]
走点心吧，还能再浮躁点吗？

**Comment by wangbojing** [comment]
古语曰：心中有佛，看世界都是佛，心中有翔，看世界满是翔。 

如果你认为，留个公众号，留个QQ交流，就是广告的话；
如果你认为，把17，18，19年的infoq，qcon，等资料，一起释放，就认为是17年的资料；
如果你认为，有个几千star，就是买的star引流的话。

兄弟，那你心中的翔多于佛啊。得去医院看看。

后续还有很多的资料，repo持续更新。
